# Generated by Django 5.0.6 on 2025-08-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_archetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='archetype',
            field=models.CharField(choices=[('intellectual', 'Наставник'), ('sergeant', 'Профессионал'), ('bro', 'Ровесник')], default='intellectual', max_length=20),
        ),
    ]
