#!/usr/bin/env python3
"""
🗄️ SIMPLE CLEAN DATABASE CREATION
Creates fresh migrations and applies them for a clean database start
"""
import os
import sys
import django
from pathlib import Path

# Setup Django
sys.path.append(str(Path(__file__).parent))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

def print_header(title):
    print(f"\n{'='*60}")
    print(f"🚀 {title}")
    print('='*60)

def main():
    print_header("CREATING CLEAN AI FITNESS COACH DATABASE")
    
    print("🎯 Creating fresh migrations and clean database...")
    
    # Step 1: Remove existing database file (SQLite)
    db_file = Path('db.sqlite3')
    if db_file.exists():
        db_file.unlink()
        print("✅ Removed existing database file")
    
    # Step 2: Remove migration files
    apps_dir = Path('apps')
    for app_dir in apps_dir.iterdir():
        if app_dir.is_dir():
            migrations_dir = app_dir / 'migrations'
            if migrations_dir.exists():
                for migration_file in migrations_dir.glob('*.py'):
                    if migration_file.name != '__init__.py':
                        migration_file.unlink()
                        print(f"🗑️  Removed {migration_file}")
    
    # Step 3: Create fresh migrations
    print("\n📋 Creating fresh migrations...")
    os.system("python manage.py makemigrations users")
    os.system("python manage.py makemigrations onboarding")
    os.system("python manage.py makemigrations workouts")
    os.system("python manage.py makemigrations achievements")
    os.system("python manage.py makemigrations content")
    
    # Step 4: Apply migrations
    print("\n🔧 Applying migrations...")
    os.system("python manage.py migrate")
    
    # Step 5: Seed essential data
    print("\n🌱 Seeding essential data...")
    seed_data()
    
    print_header("✅ CLEAN DATABASE CREATED SUCCESSFULLY")
    
    print("""
🎉 READY TO TEST:
1. Register new user: Visit /users/register/
2. Complete onboarding: Answer 5 questions + choose archetype
3. Get AI workout plan: Generated by OpenAI with your preferences
4. Start training: Daily workouts with video instructions

🗄️ DATABASE CONTAINS:
   • 5 onboarding questions with answer options
   • 6 basic exercises (push-ups, squats, etc.)
   • 4 starter achievements
   • Clean user/profile structure with XP system
""")

def seed_data():
    """Seed the database with essential data"""
    from apps.onboarding.models import OnboardingQuestion, AnswerOption
    from apps.workouts.models import Exercise
    from apps.achievements.models import Achievement
    
    # Onboarding questions
    questions_data = [
        {
            "order": 1,
            "question_text": "Какой у вас уровень опыта в фитнесе?",
            "question_type": "single_choice", 
            "ai_field_name": "experience_level",
            "options": [
                ("Новичок", "beginner"),
                ("Есть опыт", "intermediate"), 
                ("Продвинутый", "advanced")
            ]
        },
        {
            "order": 2,
            "question_text": "Какая ваша основная цель?",
            "question_type": "single_choice",
            "ai_field_name": "primary_goal", 
            "options": [
                ("Набрать мышечную массу", "bulk"),
                ("Похудеть", "cut"),
                ("Общая физическая форма", "general_fitness")
            ]
        },
        {
            "order": 3, 
            "question_text": "Сколько дней в неделю готовы тренироваться?",
            "question_type": "single_choice",
            "ai_field_name": "days_per_week",
            "options": [("3 дня", "3"), ("4 дня", "4"), ("5+ дней", "5")]
        },
        {
            "order": 4,
            "question_text": "Какое оборудование у вас есть?",
            "question_type": "single_choice",
            "ai_field_name": "available_equipment",
            "options": [
                ("Только собственный вес", "bodyweight_only"),
                ("Гантели", "dumbbells"),
                ("Полный зал", "full_gym")
            ]
        },
        {
            "order": 5,
            "question_text": "Сколько времени готовы тратить на тренировку?",
            "question_type": "single_choice", 
            "ai_field_name": "workout_duration",
            "options": [("30 минут", "30"), ("45 минут", "45"), ("60+ минут", "60")]
        }
    ]
    
    for q_data in questions_data:
        question = OnboardingQuestion.objects.create(
            order=q_data["order"],
            question_text=q_data["question_text"],
            question_type=q_data["question_type"],
            ai_field_name=q_data["ai_field_name"],
            is_required=True,
            is_active=True
        )
        print(f"✅ Created question: {question.question_text}")
        
        for i, (text, value) in enumerate(q_data["options"]):
            AnswerOption.objects.create(
                question=question,
                option_text=text,
                option_value=value,
                order=i
            )
    
    # Basic exercises
    exercises = [
        {"id": "push-ups", "name": "Отжимания", "difficulty": "beginner"},
        {"id": "squats", "name": "Приседания", "difficulty": "beginner"}, 
        {"id": "plank", "name": "Планка", "difficulty": "beginner"},
        {"id": "pull-ups", "name": "Подтягивания", "difficulty": "intermediate"},
        {"id": "deadlift", "name": "Становая тяга", "difficulty": "intermediate"},
        {"id": "bench-press", "name": "Жим лежа", "difficulty": "intermediate"},
    ]
    
    for ex in exercises:
        Exercise.objects.create(
            id=ex["id"],
            slug=ex["id"],
            name=ex["name"],
            difficulty=ex["difficulty"],
            description=f"Базовое упражнение: {ex['name']}",
            muscle_groups=["core"],
            equipment_needed=["bodyweight"],
            is_active=True
        )
        print(f"✅ Created exercise: {ex['name']}")
    
    # Basic achievements
    achievements = [
        {"slug": "first-workout", "name": "Первая тренировка", "trigger_type": "workout_count", "trigger_value": 1, "xp_reward": 100},
        {"slug": "week-streak", "name": "Неделя тренировок", "trigger_type": "streak_days", "trigger_value": 7, "xp_reward": 200},
        {"slug": "ten-workouts", "name": "10 тренировок", "trigger_type": "workout_count", "trigger_value": 10, "xp_reward": 500},
        {"slug": "level-up", "name": "Второй уровень", "trigger_type": "level_reached", "trigger_value": 2, "xp_reward": 0},
    ]
    
    for ach in achievements:
        Achievement.objects.create(
            slug=ach["slug"],
            name=ach["name"],
            description=f"Достижение: {ach['name']}",
            trigger_type=ach["trigger_type"],
            trigger_value=ach["trigger_value"],
            xp_reward=ach["xp_reward"],
            is_active=True
        )
        print(f"✅ Created achievement: {ach['name']}")

if __name__ == "__main__":
    main()