databases:
  - name: ai-fitness-coach-db
    databaseName: ai_fitness_coach
    plan: starter
    region: oregon

services:
  - type: web
    name: ai-fitness-coach
    runtime: python
    plan: starter
    region: oregon
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      python manage.py migrate --noinput
      python manage.py loaddata fixtures/exercises.json
      python manage.py loaddata fixtures/onboarding_questions.json
      python manage.py loaddata fixtures/motivational_cards.json
      python manage.py loaddata fixtures/stories.json
      python manage.py loaddata fixtures/video_clips.json
      python manage.py loaddata fixtures/achievements.json
      gunicorn config.wsgi:application --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: DATABASE_URL
        fromDatabase:
          name: ai-fitness-coach-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true