databases:
  - name: ai-fitness-coach-db
    databaseName: ai_fitness_coach
    plan: free
    region: frankfurt

services:
  - type: web
    name: ai-fitness-coach
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "python manage.py migrate --noinput && python manage.py setup_database && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --timeout 300"
    plan: starter
    region: frankfurt
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: DATABASE_URL
        fromDatabase:
          name: ai-fitness-coach-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        value: 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
      - key: DJANGO_DEBUG
        value: "False"
      - key: RENDER
        value: "true"
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 2