databases:
  - name: ai-fitness-coach-db
    databaseName: ai_fitness_coach
    plan: starter
    region: oregon

services:
  - type: web
    name: ai-fitness-coach
    runtime: python
    plan: starter
    region: oregon
    buildCommand: "pip install -r requirements-prod.txt"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: ai-fitness-coach-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DEBUG
        value: false
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true