databases:
  - name: ai-fitness-coach-db
    databaseName: ai_fitness_coach
    plan: free
    region: frankfurt

services:
  - type: web
    name: ai-fitness-coach-flask
    env: python
    buildCommand: "pip install -r requirements_new.txt"
    startCommand: "gunicorn app_new:app --bind 0.0.0.0:$PORT --timeout 300 --workers 2"
    plan: free
    region: frankfurt
    healthCheckPath: /api/health
    envVars:
      - key: FLASK_APP
        value: app_new.py
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: DATABASE_URL
        fromDatabase:
          name: ai-fitness-coach-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        value: 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
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 2