# Generated by Django 5.0.8 on 2025-08-27 16:45 - Clean Achievements Migration

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("badge_icon", models.CharField(blank=True, max_length=50)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("workout_streak", "Workout Streak"),
                            ("workouts_completed", "Workouts Completed"),
                            ("xp_earned", "XP Earned"),
                            ("level_reached", "Level Reached"),
                            ("perfect_week", "Perfect Week"),
                            ("early_bird", "Early Bird"),
                            ("consistency", "Consistency"),
                        ],
                        max_length=30,
                    ),
                ),
                ("trigger_value", models.PositiveIntegerField()),
                ("xp_reward", models.PositiveIntegerField(default=0)),
                ("icon_url", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "achievements",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="achievements.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_achievements",
                "ordering": ["-earned_at"],
                "unique_together": {("user", "achievement")},
            },
        ),
    ]