# Generated by Django 5.0.8

from django.db import migrations

class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('users', '0001_initial'),
    ]
    operations = []