# Generated by Django 5.0.6 on 2025-07-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('trigger_type', models.CharField(choices=[('workout_count', 'Total Workouts'), ('streak_days', 'Consecutive Days'), ('xp_earned', 'Experience Points'), ('plan_completed', 'Plan Completion'), ('perfect_week', 'Perfect Week'), ('confidence_tasks', 'Confidence Tasks Completed')], max_length=30)),
                ('trigger_value', models.PositiveIntegerField()),
                ('xp_reward', models.PositiveIntegerField(default=0)),
                ('icon_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'achievements',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('workouts_completed', models.PositiveIntegerField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('confidence_tasks_completed', models.PositiveIntegerField(default=0)),
                ('is_streak_day', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'daily_progress',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_achievements',
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('transaction_type', models.CharField(choices=[('workout_completed', 'Workout Completed'), ('achievement_unlocked', 'Achievement Unlocked'), ('perfect_week', 'Perfect Week Bonus'), ('confidence_task', 'Confidence Task Completed'), ('daily_login', 'Daily Login Bonus')], max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'xp_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
