# Generated by Django 5.0.8 on 2025-08-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0003_auto_20250828_1416"),
    ]

    operations = [
        # Remove poster_image field - replaced by MediaAsset system
        migrations.RemoveField(
            model_name='exercise',
            name='poster_image',
        ),
        
        # Remove alternatives M2M - replaced by MediaAsset category-based alternatives
        migrations.RemoveField(
            model_name='exercise',
            name='alternatives',
        ),
        
        # Remove muscle_groups JSON field - can be handled via MediaAsset tags
        migrations.RemoveField(
            model_name='exercise',
            name='muscle_groups',
        ),
    ]
