# Generated by Django 5.0.6 on 2025-07-15 10:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('workout_plan_bro', 'Workout Plan - Bro'), ('workout_plan_sergeant', 'Workout Plan - Sergeant'), ('workout_plan_intellectual', 'Workout Plan - Intellectual'), ('weekly_adaptation', 'Weekly Adaptation'), ('evolution_plan', 'Evolution Plan')], max_length=100, unique=True)),
                ('content', models.TextField()),
                ('variables', models.JSONField(default=list)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_prompt_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic')], max_length=50, unique=True)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('model_name', models.CharField(default='gpt-4o-mini', max_length=100)),
                ('max_tokens', models.IntegerField(default=2000)),
                ('temperature', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Provider Configuration',
                'verbose_name_plural': 'AI Provider Configurations',
                'db_table': 'ai_provider_configs',
            },
        ),
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('plan_generation', 'Plan Generation'), ('weekly_adaptation', 'Weekly Adaptation'), ('evolution_plan', 'Evolution Plan')], max_length=20)),
                ('provider', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('prompt_length', models.IntegerField()),
                ('max_tokens', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('response_length', models.IntegerField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_request_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'request_type'], name='ai_request__user_id_030b06_idx'), models.Index(fields=['created_at'], name='ai_request__created_437c73_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlanGenerationMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archetype', models.CharField(max_length=20)),
                ('generation_time_ms', models.IntegerField()),
                ('tokens_used', models.IntegerField()),
                ('total_exercises', models.IntegerField()),
                ('total_workouts', models.IntegerField()),
                ('duration_weeks', models.IntegerField()),
                ('plan_complexity_score', models.FloatField(blank=True, null=True)),
                ('exercise_variety_score', models.FloatField(blank=True, null=True)),
                ('user_satisfaction', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plan_generation_metrics',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'archetype'], name='plan_genera_user_id_f1995e_idx'), models.Index(fields=['created_at'], name='plan_genera_created_396ae8_idx')],
            },
        ),
    ]
