# Generated by Django 5.0.6 on 2025-07-23 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('image_url', models.URLField(blank=True, help_text='DEPRECATED: Use path field instead')),
                ('image', models.ImageField(blank=True, help_text='DEPRECATED: Use path field instead', null=True, upload_to='photos/quotes/')),
                ('path', models.CharField(blank=True, help_text='Relative path to image in R2 storage (e.g., "photos/quotes/card_quotes_0170.jpg")', max_length=500)),
                ('is_default_for_question', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('goal', 'Goal-related'), ('experience', 'Experience-related'), ('limitation', 'Limitation-related'), ('general', 'General motivation'), ('response', 'Response-specific')], default='response', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'motivational_cards',
            },
        ),
        migrations.CreateModel(
            name='OnboardingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(unique=True)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('number', 'Number Input'), ('text', 'Text Input'), ('scale', 'Scale (1-5)'), ('body_map', 'Body Map Selection')], max_length=20)),
                ('block_name', models.CharField(blank=True, max_length=100)),
                ('block_order', models.PositiveIntegerField(default=1)),
                ('is_block_separator', models.BooleanField(default=False)),
                ('separator_text', models.TextField(blank=True)),
                ('min_value', models.IntegerField(blank=True, null=True)),
                ('max_value', models.IntegerField(blank=True, null=True)),
                ('scale_min_label', models.CharField(blank=True, max_length=50)),
                ('scale_max_label', models.CharField(blank=True, max_length=50)),
                ('help_text', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('depends_on_answer', models.CharField(blank=True, max_length=100)),
                ('ai_field_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'onboarding_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=200)),
                ('option_value', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('motivational_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_options', to='onboarding.motivationalcard')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='onboarding.onboardingquestion')),
            ],
            options={
                'db_table': 'answer_options',
                'ordering': ['order'],
                'unique_together': {('question', 'order')},
            },
        ),
        migrations.CreateModel(
            name='OnboardingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_request_sent_at', models.DateTimeField(blank=True, null=True)),
                ('ai_response_received_at', models.DateTimeField(blank=True, null=True)),
                ('ai_request_data', models.JSONField(blank=True, null=True)),
                ('ai_response_data', models.JSONField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'onboarding_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserOnboardingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('answer_number', models.IntegerField(blank=True, null=True)),
                ('answer_scale', models.IntegerField(blank=True, null=True)),
                ('answer_body_map', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer_options', models.ManyToManyField(blank=True, to='onboarding.answeroption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.onboardingquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_onboarding_responses',
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.AddField(
            model_name='motivationalcard',
            name='answer_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motivational_cards', to='onboarding.answeroption'),
        ),
        migrations.AddField(
            model_name='motivationalcard',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motivational_cards', to='onboarding.onboardingquestion'),
        ),
        migrations.AddField(
            model_name='onboardingquestion',
            name='depends_on_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_questions', to='onboarding.onboardingquestion'),
        ),
        migrations.AlterUniqueTogether(
            name='motivationalcard',
            unique_together={('question', 'answer_option')},
        ),
    ]
