# Generated by Django 5.0.8 on 2025-08-19 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "exercise_slug",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "exercises",
                "ordering": ["exercise_slug"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_data", models.JSONField()),
                ("duration_weeks", models.IntegerField(default=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "workout_plans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyWorkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.IntegerField()),
                ("playlist", models.JSONField()),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_workouts",
                        to="workouts.workoutplan",
                    ),
                ),
            ],
            options={
                "db_table": "daily_workouts",
                "ordering": ["day_number"],
                "unique_together": {("plan", "day_number")},
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="\n                    DO $$\n                    BEGIN\n                        IF to_regclass('public.workout_plans') IS NOT NULL THEN\n                            ALTER TABLE workout_plans\n                            ADD COLUMN IF NOT EXISTS ai_analysis JSONB;\n                        ELSIF to_regclass('public.workouts_workoutplan') IS NOT NULL THEN\n                            ALTER TABLE workouts_workoutplan\n                            ADD COLUMN IF NOT EXISTS ai_analysis JSONB;\n                        END IF;\n                    END\n                    $$;\n                    ",
                    reverse_sql="\n                    DO $$\n                    BEGIN\n                        IF to_regclass('public.workout_plans') IS NOT NULL THEN\n                            ALTER TABLE workout_plans\n                            DROP COLUMN IF EXISTS ai_analysis;\n                        ELSIF to_regclass('public.workouts_workoutplan') IS NOT NULL THEN\n                            ALTER TABLE workouts_workoutplan\n                            DROP COLUMN IF EXISTS ai_analysis;\n                        END IF;\n                    END\n                    $$;\n                    ",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="workoutplan",
                    name="ai_analysis",
                    field=models.JSONField(blank=True, null=True),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="\n                    DO $$\n                    BEGIN\n                        IF to_regclass('public.workout_plans') IS NOT NULL THEN\n                            ALTER TABLE workout_plans\n                            ADD COLUMN IF NOT EXISTS is_confirmed BOOLEAN NOT NULL DEFAULT FALSE;\n                        ELSIF to_regclass('public.workouts_workoutplan') IS NOT NULL THEN\n                            ALTER TABLE workouts_workoutplan\n                            ADD COLUMN IF NOT EXISTS is_confirmed BOOLEAN NOT NULL DEFAULT FALSE;\n                        END IF;\n                    END\n                    $$;\n                    ",
                    reverse_sql="\n                    DO $$\n                    BEGIN\n                        IF to_regclass('public.workout_plans') IS NOT NULL THEN\n                            ALTER TABLE workout_plans\n                            DROP COLUMN IF EXISTS is_confirmed;\n                        ELSIF to_regclass('public.workouts_workoutplan') IS NOT NULL THEN\n                            ALTER TABLE workouts_workoutplan\n                            DROP COLUMN IF EXISTS is_confirmed;\n                        END IF;\n                    END\n                    $$;\n                    ",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="workoutplan",
                    name="is_confirmed",
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="\n                    DO $$\n                    BEGIN\n                        IF to_regclass('public.daily_workouts') IS NOT NULL THEN\n                            ALTER TABLE daily_workouts\n                            ADD COLUMN IF NOT EXISTS week_number INTEGER NOT NULL DEFAULT 1;\n                        ELSIF to_regclass('public.workouts_dailyworkout') IS NOT NULL THEN\n                            ALTER TABLE workouts_dailyworkout\n                            ADD COLUMN IF NOT EXISTS week_number INTEGER NOT NULL DEFAULT 1;\n                        END IF;\n                    END\n                    $$;\n                    ",
                    reverse_sql="\n                    DO $$\n                    BEGIN\n                        IF to_regclass('public.daily_workouts') IS NOT NULL THEN\n                            ALTER TABLE daily_workouts\n                            DROP COLUMN IF EXISTS week_number;\n                        ELSIF to_regclass('public.workouts_dailyworkout') IS NOT NULL THEN\n                            ALTER TABLE workouts_dailyworkout\n                            DROP COLUMN IF EXISTS week_number;\n                        END IF;\n                    END\n                    $$;\n                    ",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="dailyworkout",
                    name="week_number",
                    field=models.IntegerField(default=1),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="\n                    DO $$\n                    BEGIN\n                        IF to_regclass('public.daily_workouts') IS NOT NULL THEN\n                            ALTER TABLE daily_workouts\n                            ADD COLUMN IF NOT EXISTS name VARCHAR(200) NOT NULL DEFAULT '';\n                        ELSIF to_regclass('public.workouts_dailyworkout') IS NOT NULL THEN\n                            ALTER TABLE workouts_dailyworkout\n                            ADD COLUMN IF NOT EXISTS name VARCHAR(200) NOT NULL DEFAULT '';\n                        END IF;\n                    END\n                    $$;\n                    ",
                    reverse_sql="\n                    DO $$\n                    BEGIN\n                        IF to_regclass('public.daily_workouts') IS NOT NULL THEN\n                            ALTER TABLE daily_workouts\n                            DROP COLUMN IF EXISTS name;\n                        ELSIF to_regclass('public.workouts_dailyworkout') IS NOT NULL THEN\n                            ALTER TABLE workouts_dailyworkout\n                            DROP COLUMN IF EXISTS name;\n                        END IF;\n                    END\n                    $$;\n                    ",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="dailyworkout",
                    name="name",
                    field=models.CharField(default="", max_length=200),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="\n                    DO $$\n                    BEGIN\n                        IF to_regclass('public.daily_workouts') IS NOT NULL THEN\n                            ALTER TABLE daily_workouts\n                            ADD COLUMN IF NOT EXISTS is_rest_day BOOLEAN NOT NULL DEFAULT FALSE;\n                        ELSIF to_regclass('public.workouts_dailyworkout') IS NOT NULL THEN\n                            ALTER TABLE workouts_dailyworkout\n                            ADD COLUMN IF NOT EXISTS is_rest_day BOOLEAN NOT NULL DEFAULT FALSE;\n                        END IF;\n                    END\n                    $$;\n                    ",
                    reverse_sql="\n                    DO $$\n                    BEGIN\n                        IF to_regclass('public.daily_workouts') IS NOT NULL THEN\n                            ALTER TABLE daily_workouts\n                            DROP COLUMN IF EXISTS is_rest_day;\n                        ELSIF to_regclass('public.workouts_dailyworkout') IS NOT NULL THEN\n                            ALTER TABLE workouts_dailyworkout\n                            DROP COLUMN IF EXISTS is_rest_day;\n                        END IF;\n                    END\n                    $$;\n                    ",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="dailyworkout",
                    name="is_rest_day",
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="\n                    DO $$\n                    BEGIN\n                        IF to_regclass('public.daily_workouts') IS NOT NULL THEN\n                            ALTER TABLE daily_workouts\n                            ADD COLUMN IF NOT EXISTS feedback_rating INTEGER;\n                        ELSIF to_regclass('public.workouts_dailyworkout') IS NOT NULL THEN\n                            ALTER TABLE workouts_dailyworkout\n                            ADD COLUMN IF NOT EXISTS feedback_rating INTEGER;\n                        END IF;\n                    END\n                    $$;\n                    ",
                    reverse_sql="\n                    DO $$\n                    BEGIN\n                        IF to_regclass('public.daily_workouts') IS NOT NULL THEN\n                            ALTER TABLE daily_workouts\n                            DROP COLUMN IF EXISTS feedback_rating;\n                        ELSIF to_regclass('public.workouts_dailyworkout') IS NOT NULL THEN\n                            ALTER TABLE workouts_dailyworkout\n                            DROP COLUMN IF EXISTS feedback_rating;\n                        END IF;\n                    END\n                    $$;\n                    ",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="dailyworkout",
                    name="feedback_rating",
                    field=models.IntegerField(blank=True, null=True),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="\n                    DO $$\n                    BEGIN\n                        IF to_regclass('public.daily_workouts') IS NOT NULL THEN\n                            ALTER TABLE daily_workouts\n                            ADD COLUMN IF NOT EXISTS feedback_note TEXT NOT NULL DEFAULT '';\n                        ELSIF to_regclass('public.workouts_dailyworkout') IS NOT NULL THEN\n                            ALTER TABLE workouts_dailyworkout\n                            ADD COLUMN IF NOT EXISTS feedback_note TEXT NOT NULL DEFAULT '';\n                        END IF;\n                    END\n                    $$;\n                    ",
                    reverse_sql="\n                    DO $$\n                    BEGIN\n                        IF to_regclass('public.daily_workouts') IS NOT NULL THEN\n                            ALTER TABLE daily_workouts\n                            DROP COLUMN IF EXISTS feedback_note;\n                        ELSIF to_regclass('public.workouts_dailyworkout') IS NOT NULL THEN\n                            ALTER TABLE workouts_dailyworkout\n                            DROP COLUMN IF EXISTS feedback_note;\n                        END IF;\n                    END\n                    $$;\n                    ",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="dailyworkout",
                    name="feedback_note",
                    field=models.TextField(blank=True, default=""),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="\n                    DO $$\n                    BEGIN\n                        IF to_regclass('public.daily_workouts') IS NOT NULL THEN\n                            ALTER TABLE daily_workouts\n                            ADD COLUMN IF NOT EXISTS confidence_task TEXT NOT NULL DEFAULT '';\n                        ELSIF to_regclass('public.workouts_dailyworkout') IS NOT NULL THEN\n                            ALTER TABLE workouts_dailyworkout\n                            ADD COLUMN IF NOT EXISTS confidence_task TEXT NOT NULL DEFAULT '';\n                        END IF;\n                    END\n                    $$;\n                    ",
                    reverse_sql="\n                    DO $$\n                    BEGIN\n                        IF to_regclass('public.daily_workouts') IS NOT NULL THEN\n                            ALTER TABLE daily_workouts\n                            DROP COLUMN IF EXISTS confidence_task;\n                        ELSIF to_regclass('public.workouts_dailyworkout') IS NOT NULL THEN\n                            ALTER TABLE workouts_dailyworkout\n                            DROP COLUMN IF EXISTS confidence_task;\n                        END IF;\n                    END\n                    $$;\n                    ",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="dailyworkout",
                    name="confidence_task",
                    field=models.TextField(blank=True, default=""),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="\n                    DO $$\n                    BEGIN\n                        IF to_regclass('public.daily_workouts') IS NOT NULL THEN\n                            ALTER TABLE daily_workouts\n                            ADD COLUMN IF NOT EXISTS substitutions JSONB NOT NULL DEFAULT '{}';\n                        ELSIF to_regclass('public.workouts_dailyworkout') IS NOT NULL THEN\n                            ALTER TABLE workouts_dailyworkout\n                            ADD COLUMN IF NOT EXISTS substitutions JSONB NOT NULL DEFAULT '{}';\n                        END IF;\n                    END\n                    $$;\n                    ",
                    reverse_sql="\n                    DO $$\n                    BEGIN\n                        IF to_regclass('public.daily_workouts') IS NOT NULL THEN\n                            ALTER TABLE daily_workouts\n                            DROP COLUMN IF EXISTS substitutions;\n                        ELSIF to_regclass('public.workouts_dailyworkout') IS NOT NULL THEN\n                            ALTER TABLE workouts_dailyworkout\n                            DROP COLUMN IF EXISTS substitutions;\n                        END IF;\n                    END\n                    $$;\n                    ",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="dailyworkout",
                    name="substitutions",
                    field=models.JSONField(default=dict),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="\n                    DO $$\n                    BEGIN\n                        IF to_regclass('public.daily_workouts') IS NOT NULL THEN\n                            ALTER TABLE daily_workouts\n                            ADD COLUMN IF NOT EXISTS exercises JSONB NOT NULL DEFAULT '[]';\n                        ELSIF to_regclass('public.workouts_dailyworkout') IS NOT NULL THEN\n                            ALTER TABLE workouts_dailyworkout\n                            ADD COLUMN IF NOT EXISTS exercises JSONB NOT NULL DEFAULT '[]';\n                        END IF;\n                    END\n                    $$;\n                    ",
                    reverse_sql="\n                    DO $$\n                    BEGIN\n                        IF to_regclass('public.daily_workouts') IS NOT NULL THEN\n                            ALTER TABLE daily_workouts\n                            DROP COLUMN IF EXISTS exercises;\n                        ELSIF to_regclass('public.workouts_dailyworkout') IS NOT NULL THEN\n                            ALTER TABLE workouts_dailyworkout\n                            DROP COLUMN IF EXISTS exercises;\n                        END IF;\n                    END\n                    $$;\n                    ",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="dailyworkout",
                    name="exercises",
                    field=models.JSONField(default=list),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="\n                    DO $$\n                    BEGIN\n                        IF to_regclass('public.daily_workouts') IS NOT NULL THEN\n                            ALTER TABLE daily_workouts\n                            ADD COLUMN IF NOT EXISTS started_at TIMESTAMPTZ;\n                        ELSIF to_regclass('public.workouts_dailyworkout') IS NOT NULL THEN\n                            ALTER TABLE workouts_dailyworkout\n                            ADD COLUMN IF NOT EXISTS started_at TIMESTAMPTZ;\n                        END IF;\n                    END\n                    $$;\n                    ",
                    reverse_sql="\n                    DO $$\n                    BEGIN\n                        IF to_regclass('public.daily_workouts') IS NOT NULL THEN\n                            ALTER TABLE daily_workouts\n                            DROP COLUMN IF EXISTS started_at;\n                        ELSIF to_regclass('public.workouts_dailyworkout') IS NOT NULL THEN\n                            ALTER TABLE workouts_dailyworkout\n                            DROP COLUMN IF EXISTS started_at;\n                        END IF;\n                    END\n                    $$;\n                    ",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="dailyworkout",
                    name="started_at",
                    field=models.DateTimeField(blank=True, null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="dailyworkout",
            name="confidence_task",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="dailyworkout",
            name="feedback_note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="dailyworkout",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="dailyworkout",
            name="playlist",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="dailyworkout",
            name="week_number",
            field=models.IntegerField(),
        ),
    ]
