# Generated by Django 5.0.8 on 2025-09-01 20:46

from django.db import migrations
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create core tables with IF NOT EXISTS for safety
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS r2_videos (
                code VARCHAR(150) PRIMARY KEY,
                name VARCHAR(200) NOT NULL,
                description TEXT DEFAULT '',
                category VARCHAR(20) NOT NULL,
                display_title VARCHAR(200) DEFAULT '',
                display_description TEXT DEFAULT '',
                is_featured BOOLEAN DEFAULT false,
                sort_order INTEGER DEFAULT 0,
                archetype VARCHAR(20) DEFAULT ''
            );

            CREATE TABLE IF NOT EXISTS daily_playlist_items (
                id SERIAL PRIMARY KEY,
                day_id INTEGER NOT NULL,
                "order" INTEGER NOT NULL,
                role VARCHAR(20) NOT NULL,
                video_code VARCHAR(150) NOT NULL REFERENCES r2_videos(code),
                duration_seconds INTEGER,
                overlay JSONB DEFAULT '{}'::jsonb,
                UNIQUE (day_id, "order")
            );

            CREATE INDEX IF NOT EXISTS r2_videos_category_idx ON r2_videos (category);
            CREATE INDEX IF NOT EXISTS r2_videos_archetype_idx ON r2_videos (archetype);
            CREATE INDEX IF NOT EXISTS daily_playlist_items_day_order_idx ON daily_playlist_items (day_id, "order");
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS daily_playlist_items;
            DROP TABLE IF EXISTS r2_videos;
            """
        ),
    ]
