# Generated by Django 5.0.8 on 2025-08-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videoclip",
            name="type",
            field=models.CharField(
                choices=[
                    ("technique", "Technique"),
                    ("mistake", "Common Mistake"),
                    ("instruction", "Instruction"),
                    ("reminder", "Reminder"),
                    ("intro", "Daily Intro"),
                    ("weekly", "Weekly Motivation"),
                    ("progress", "Progress Milestone"),
                    ("final", "Final Congratulation"),
                ],
                max_length=20,
            ),
        ),
    ]
