# Generated by Django 5.0.8 on 2025-08-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='ai_analysis',
            field=models.JSONField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyworkout',
            name='week_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dailyworkout',
            name='name',
            field=models.CharField(max_length=200, default=''),
        ),
        migrations.AddField(
            model_name='dailyworkout',
            name='is_rest_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyworkout',
            name='feedback_rating',
            field=models.IntegerField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='dailyworkout',
            name='feedback_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dailyworkout',
            name='confidence_task',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dailyworkout',
            name='substitutions',
            field=models.JSONField(default=dict),
        ),
    ]
