# Generated by Django 5.0.6 on 2025-07-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoclip',
            name='type',
            field=models.CharField(choices=[('technique', 'Technique'), ('mistake', 'Common Mistake'), ('intro', 'Introduction'), ('outro', 'Outro'), ('support', 'Support/Motivation')], max_length=20),
        ),
    ]
