# Generated by Django 5.0.6 on 2025-07-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
