# Generated by Django 5.0.8 on 2025-08-18 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0002_add_new_video_types"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="mistake_video_url",
        ),
        migrations.RemoveField(
            model_name="exercise",
            name="technique_video_url",
        ),
    ]
