# Generated by Django 5.0.8 on 2025-08-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0002_squashed_compat"),
    ]

    operations = [
        # Add name field to WorkoutPlan if it doesn't exist
        # This handles the case where production DB was created before this field was added
        migrations.RunSQL(
            "ALTER TABLE workout_plans ADD COLUMN IF NOT EXISTS name VARCHAR(200) DEFAULT 'My Workout Plan';",
            reverse_sql="ALTER TABLE workout_plans DROP COLUMN IF EXISTS name;"
        ),
        # Update any existing records with empty names
        migrations.RunSQL(
            "UPDATE workout_plans SET name = 'My Workout Plan' WHERE name IS NULL OR name = '';",
            reverse_sql=migrations.RunSQL.noop
        ),
        # Make the field NOT NULL after setting default values
        migrations.RunSQL(
            "ALTER TABLE workout_plans ALTER COLUMN name SET NOT NULL;",
            reverse_sql="ALTER TABLE workout_plans ALTER COLUMN name DROP NOT NULL;"
        ),
    ]
