# Generated by Django 5.0.8 on 2025-08-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("workouts", "0003_update_csvexercise_r2_structure"),
        ("workouts", "0004_add_missing_csvexercise_columns"),
        ("workouts", "0005_remove_unnecessary_category_field"),
    ]

    dependencies = [
        ("workouts", "0006_merge_0002_branches"),
    ]

    operations = [
        # Создаём базовую таблицу для чистых установок (идемпотентно)
        migrations.RunSQL(
            sql=(
                'CREATE TABLE IF NOT EXISTS "csv_exercises" ('
                '  "id" varchar(64) NOT NULL PRIMARY KEY'
                ');'
            ),
            reverse_sql=(
                # Ничего не удаляем при откате
                '/* no-op: keep csv_exercises */'
            ),
        ),

        # ВАЖНО: синхронизируем "state" с фактической таблицей для чистых установок  
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelTable(
                    name='csvexercise',
                    table='csv_exercises',  # используем кастомное имя таблицы из Meta
                ),
            ],
        ),

        # Update ID field help text
        migrations.AlterField(
            model_name="csvexercise",
            name="id",
            field=models.CharField(
                help_text="warmup_01, main_001, endurance_01, relaxation_01",
                max_length=20,
                primary_key=True,
            ),
        ),
        
        # Rename difficulty to level if it exists
        # ЗАКОММЕНТИРОВАНО: поле difficulty не существует в state на чистой базе
        # migrations.RenameField(
        #     model_name='csvexercise',
        #     old_name='difficulty',
        #     new_name='level',
        # ),

        # Add R2 structure fields
        migrations.AddField(
            model_name='csvexercise',
            name='exercise_type',
            field=models.CharField(max_length=120, blank=True),
        ),
        migrations.AddField(
            model_name='csvexercise',
            name='muscle_group',
            field=models.CharField(max_length=120, blank=True),
        ),
        migrations.AddField(
            model_name='csvexercise',
            name='name_ru',
            field=models.CharField(max_length=120, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvexercise',
            name='name_en',
            field=models.CharField(max_length=120, blank=True),
        ),
        migrations.AddField(
            model_name='csvexercise',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='csvexercise',
            name='ai_tags',
            field=models.JSONField(default=list, blank=True),
        ),
        migrations.AddField(
            model_name='csvexercise',
            name='r2_slug',
            field=models.CharField(max_length=50, blank=True, help_text='Original R2 slug format'),
        ),
        migrations.AddField(
            model_name='csvexercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='csvexercise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, blank=True),
        ),
        
        # Remove category field
        migrations.RemoveField(
            model_name='csvexercise',
            name='category',
        ),
        
        # Add level field (since RenameField was commented out)
        migrations.AddField(
            model_name='csvexercise',
            name='level',
            field=models.CharField(max_length=20, default='beginner'),
        ),
    ]