# Generated by Django 5.0.8 on 2025-08-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0002_add_missing_daily_workout_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyworkout",
            name="exercises",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="dailyworkout",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dailyworkout",
            name="confidence_task",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="dailyworkout",
            name="feedback_note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="dailyworkout",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="dailyworkout",
            name="playlist",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="dailyworkout",
            name="week_number",
            field=models.IntegerField(),
        ),
    ]
