# Generated by Django 5.0.8 on 2025-11-16 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailyworkout",
            options={"ordering": ["week_number", "day_number"]},
        ),
        migrations.AlterUniqueTogether(
            name="dailyworkout",
            unique_together={("plan", "week_number", "day_number")},
        ),
    ]
