# Generated by Django 5.0.6 on 2025-07-14 13:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workoutplan_is_confirmed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('overall_difficulty', models.CharField(choices=[('too_easy', 'Слишком легко'), ('just_right', 'В самый раз'), ('too_hard', 'Слишком тяжело'), ('varied', 'По-разному')], default='just_right', max_length=20)),
                ('energy_level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=20)),
                ('motivation_level', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], default='medium', max_length=20)),
                ('most_challenging_exercises', models.JSONField(default=list)),
                ('favorite_exercises', models.JSONField(default=list)),
                ('strength_progress', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('confidence_progress', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('wants_more_cardio', models.BooleanField(default=False)),
                ('wants_more_strength', models.BooleanField(default=False)),
                ('wants_shorter_workouts', models.BooleanField(default=False)),
                ('wants_longer_workouts', models.BooleanField(default=False)),
                ('what_worked_well', models.TextField(blank=True)),
                ('what_needs_improvement', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_feedbacks', to='workouts.workoutplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'weekly_feedbacks',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'plan', 'week_number')},
            },
        ),
    ]
