# Generated by Django 5.0.6 on 2025-07-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_videoclip_type'),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="technique_video_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="mistake_video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
