# Generated by Django 5.0.8 on 2025-08-28 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0002_add_poster_image_column"),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('intro', 'Intro'), ('warmup', 'Warm-up'), ('main', 'Main'), ('transition', 'Transition'), ('cooldown', 'Cooldown'), ('motivation', 'Motivation'), ('breathing', 'Breathing')], max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('overlay', models.JSONField(blank=True, default=dict)),
                ('day', models.ForeignKey(on_delete=models.CASCADE, related_name='playlist_items', to='workouts.dailyworkout')),
                ('media', models.ForeignKey(on_delete=models.PROTECT, related_name='used_in_playlist', to='content.mediaasset')),
            ],
            options={
                'db_table': 'daily_playlist_items',
                'ordering': ['day_id', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailyplaylistitem',
            constraint=models.UniqueConstraint(fields=('day', 'order'), name='unique_day_order'),
        ),
    ]
