# Generated by Django 5.0.6 on 2025-07-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_fix_equipment_needed_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
