# Generated by Django 5.0.6 on 2025-07-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_weeklyfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='alternatives',
            field=models.ManyToManyField(blank=True, help_text='Упражнения-замены', related_name='alternative_for', to='workouts.exercise'),
        ),
    ]
