# Generated by Django 5.0.6 on 2025-07-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_add_missing_exercise_video_cols'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoclip',
            name='is_placeholder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='mistake_video_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='technique_video_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
