# Generated by Django 5.0.6 on 2025-07-28 17:18

from django.db import migrations, models
from django.db import connection


def add_equipment_field_if_not_exists(apps, schema_editor):
    """Add equipment field only if it doesn't exist"""
    with connection.cursor() as cursor:
        # Check if column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='exercises' AND column_name='equipment'
        """)
        
        if not cursor.fetchone():
            # Column doesn't exist, add it
            cursor.execute("""
                ALTER TABLE exercises 
                ADD COLUMN equipment VARCHAR(50) DEFAULT 'bodyweight' NOT NULL
            """)


def remove_equipment_field(apps, schema_editor):
    """Remove equipment field"""
    with connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE exercises 
            DROP COLUMN IF EXISTS equipment
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_videoclip_is_placeholder_alter_exercise_created_at_and_more'),
    ]

    operations = [
        migrations.RunPython(add_equipment_field_if_not_exists, remove_equipment_field),
    ]