# Generated by Django 5.0.6 on 2025-07-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_exercise_alternatives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoclip',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
