# Generated by Django 5.0.6 on 2025-07-24 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_add_exercise_is_active_safe'),
    ]

    operations = [
        # Add defaults to URL fields safely
        migrations.RunSQL(
            """
            ALTER TABLE exercises
              ALTER COLUMN technique_video_url SET DEFAULT '';
            """,
            reverse_sql="""
            ALTER TABLE exercises
              ALTER COLUMN technique_video_url DROP DEFAULT;
            """,
        ),
        migrations.RunSQL(
            """
            ALTER TABLE exercises
              ALTER COLUMN mistake_video_url SET DEFAULT '';
            """,
            reverse_sql="""
            ALTER TABLE exercises
              ALTER COLUMN mistake_video_url DROP DEFAULT;
            """,
        ),
        # Update existing NULL values
        migrations.RunSQL(
            """
            UPDATE exercises 
            SET technique_video_url = '' 
            WHERE technique_video_url IS NULL;
            """,
            reverse_sql="",
        ),
        migrations.RunSQL(
            """
            UPDATE exercises 
            SET mistake_video_url = '' 
            WHERE mistake_video_url IS NULL;
            """,
            reverse_sql="",
        ),
    ]
