# Generated by Django 5.0.8 on 2025-08-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0006_explainervideo_finalvideo_weeklylesson_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft - awaiting confirmation"),
                    ("CONFIRMED", "Confirmed - ready to start"),
                    ("ACTIVE", "Active - in progress"),
                    ("COMPLETED", "Completed"),
                ],
                default="DRAFT",
                max_length=10,
            ),
        ),
    ]
