# Generated by Django 5.0.6 on 2025-07-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_exercise_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='ai_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
