# Generated by Django 5.0.8 on 2025-08-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0007_add_status_to_workout_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoclip",
            name="r2_key",
            field=models.CharField(
                blank=True,
                help_text="R2 storage key/path for direct access",
                max_length=500,
            ),
        ),
    ]
