# Generated by Django 5.0.6 on 2025-08-02 12:46

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_add_ai_analysis_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVExercise',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name_ru', models.CharField(max_length=120)),
                ('name_en', models.CharField(blank=True, max_length=120)),
                ('level', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('muscle_group', models.CharField(blank=True, max_length=50)),
                ('exercise_type', models.CharField(blank=True, max_length=50)),
                ('ai_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None)),
            ],
            options={
                'verbose_name': 'Упражнение CSV',
                'verbose_name_plural': 'Упражнения CSV',
                'db_table': 'csv_exercises',
            },
        ),
        migrations.CreateModel(
            name='ExplainerVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archetype', models.CharField(choices=[('111', 'Наставник'), ('222', 'Профессионал'), ('333', 'Ровесник')], max_length=3)),
                ('script', models.TextField()),
                ('locale', models.CharField(default='ru', max_length=5)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='workouts.csvexercise')),
            ],
            options={
                'verbose_name': 'Видео-объяснение',
                'verbose_name_plural': 'Видео-объяснения',
                'db_table': 'explainer_videos',
                'unique_together': {('exercise', 'archetype', 'locale')},
            },
        ),
    ]
