# Generated by Django 5.0.6 on 2025-08-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_csvexercise_explainervideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalVideo',
            fields=[
                ('arch', models.CharField(choices=[('111', 'Н'), ('222', 'П'), ('333', 'Р')], max_length=3, primary_key=True, serialize=False)),
                ('locale', models.CharField(default='ru', max_length=5)),
                ('script', models.TextField()),
            ],
            options={
                'db_table': 'final_videos',
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(default='bodyweight', help_text='Основной инвентарь: bodyweight | dumbbell | barbell …', max_length=50),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='is_placeholder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='ai_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='mistake_video_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='technique_video_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='WeeklyLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField()),
                ('archetype', models.CharField(choices=[('111', 'Н'), ('222', 'П'), ('333', 'Р')], max_length=3)),
                ('locale', models.CharField(default='ru', max_length=5)),
                ('title', models.CharField(max_length=120)),
                ('script', models.TextField()),
            ],
            options={
                'db_table': 'weekly_lessons',
                'ordering': ['week'],
                'unique_together': {('week', 'archetype', 'locale')},
            },
        ),
    ]
