# Generated by Django 5.0.6 on 2025-08-06 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_finalvideo_exercise_equipment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField()),
                ('archetype', models.CharField(choices=[('111', 'Н'), ('222', 'П'), ('333', 'Р')], max_length=3)),
                ('lesson_title', models.CharField(max_length=120)),
                ('lesson_script', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'weekly_notifications',
                'ordering': ['-week', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='weekly_noti_user_id_ddf0af_idx'), models.Index(fields=['week'], name='weekly_noti_week_45b255_idx')],
                'unique_together': {('user', 'week')},
            },
        ),
    ]
