# Generated by Django 5.0.6 on 2025-08-06 14:06

from django.db import connection, migrations


def add_duration_sec_field_safe(apps, schema_editor):
    """Safely add duration_sec field to weekly_lessons table"""
    db_vendor = connection.vendor
    
    with connection.cursor() as cursor:
        try:
            if db_vendor == 'postgresql':
                # Check if duration_sec column exists
                cursor.execute("""
                    SELECT column_name 
                    FROM information_schema.columns 
                    WHERE table_name = 'weekly_lessons' AND column_name = 'duration_sec'
                """)
                if not cursor.fetchone():
                    cursor.execute("""
                        ALTER TABLE weekly_lessons 
                        ADD COLUMN duration_sec integer DEFAULT 180
                    """)
            else:
                # For SQLite, try to add and ignore if exists
                try:
                    cursor.execute("""
                        ALTER TABLE weekly_lessons 
                        ADD COLUMN duration_sec integer DEFAULT 180
                    """)
                except Exception:
                    pass  # Column already exists
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0011_safe_equipment_field_and_models'),
    ]

    operations = [
        migrations.RunPython(
            add_duration_sec_field_safe,
            migrations.RunPython.noop
        ),
    ]
