# Generated by Django 5.0.6 on 2025-08-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0012_add_duration_sec_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalVideo',
            fields=[
                ('arch', models.CharField(choices=[('111', 'Н'), ('222', 'П'), ('333', 'Р')], max_length=3, primary_key=True, serialize=False)),
                ('locale', models.CharField(default='ru', max_length=5)),
                ('script', models.TextField()),
            ],
            options={
                'db_table': 'final_videos',
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(default='bodyweight', help_text='Основной инвентарь: bodyweight | dumbbell | barbell …', max_length=50),
        ),
        migrations.AddField(
            model_name='exercise',
            name='poster_image',
            field=models.ImageField(blank=True, help_text='Poster image for video player', null=True, upload_to='photos/workout/'),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='is_placeholder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='r2_archetype',
            field=models.CharField(blank=True, choices=[('bro', 'Бро'), ('sergeant', 'Сержант'), ('intellectual', 'Интеллектуал'), ('peer', 'Ровесник'), ('professional', 'Успешный профессионал'), ('mentor', 'Мудрый наставник')], help_text='Archetype for R2 videos', max_length=20),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='r2_file',
            field=models.FileField(blank=True, help_text='Video file in R2 storage', null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='r2_kind',
            field=models.CharField(blank=True, choices=[('technique', 'Technique'), ('mistake', 'Common Mistake'), ('instruction', 'Instruction'), ('intro', 'Introduction'), ('weekly', 'Weekly Motivation'), ('closing', 'Closing'), ('reminder', 'Reminder'), ('explain', 'Exercise Explanation')], help_text='Video type for R2 organization', max_length=20),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='script_text',
            field=models.TextField(blank=True, help_text='Video script or content'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='ai_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='mistake_video_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='technique_video_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='videoclip',
            name='archetype',
            field=models.CharField(choices=[('bro', 'Бро'), ('sergeant', 'Сержант'), ('intellectual', 'Интеллектуал'), ('peer', 'Ровесник'), ('professional', 'Успешный профессионал'), ('mentor', 'Мудрый наставник')], max_length=20),
        ),
        migrations.CreateModel(
            name='WeeklyLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField()),
                ('archetype', models.CharField(choices=[('111', 'Н'), ('222', 'П'), ('333', 'Р')], max_length=3)),
                ('locale', models.CharField(default='ru', max_length=5)),
                ('title', models.CharField(max_length=120)),
                ('script', models.TextField()),
                ('duration_sec', models.PositiveIntegerField(default=180, help_text='Estimated reading time in seconds')),
            ],
            options={
                'db_table': 'weekly_lessons',
                'ordering': ['week'],
                'unique_together': {('week', 'archetype', 'locale')},
            },
        ),
    ]
