# Generated by Django 5.0.6 on 2025-08-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0012_add_duration_sec_field'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""CREATE TABLE IF NOT EXISTS final_videos (
                arch varchar(20) PRIMARY KEY,
                locale varchar(5) DEFAULT 'ru',
                script text
            );""",
            reverse_sql="DROP TABLE IF EXISTS final_videos;"
        ),
        migrations.RunSQL(
            sql="""CREATE TABLE IF NOT EXISTS weekly_lessons (
                id bigint PRIMARY KEY,
                week smallint,
                archetype varchar(20),
                locale varchar(5) DEFAULT 'ru',
                title varchar(120),
                script text,
                duration_sec integer DEFAULT 180,
                CONSTRAINT weekly_lessons_week_archetype_locale_uniq UNIQUE (week, archetype, locale)
            );""",
            reverse_sql="DROP TABLE IF EXISTS weekly_lessons;"
        ),
        migrations.RemoveIndex(
            model_name='videoclip',
            name='video_clips_exercis_cde9f7_idx',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='mistake_video_url',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='technique_video_url',
        ),
        migrations.AlterUniqueTogether(
            name='videoclip',
            unique_together={('exercise', 'r2_kind', 'archetype', 'model_name', 'reminder_text')},
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(default='bodyweight', help_text='Основной инвентарь: bodyweight | dumbbell | barbell …', max_length=50),
        ),
        migrations.AddField(
            model_name='exercise',
            name='poster_image',
            field=models.ImageField(blank=True, help_text='Poster image for video player', null=True, upload_to='photos/workout/'),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='is_placeholder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='r2_archetype',
            field=models.CharField(blank=True, choices=[('peer', 'Ровесник'), ('professional', 'Успешный профессионал'), ('mentor', 'Мудрый наставник')], help_text='Archetype for R2 videos', max_length=20),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='r2_file',
            field=models.FileField(blank=True, help_text='Video file in R2 storage', null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='r2_kind',
            field=models.CharField(choices=[('technique', 'Technique'), ('mistake', 'Common Mistake'), ('instruction', 'Instruction'), ('intro', 'Introduction'), ('weekly', 'Weekly Motivation'), ('closing', 'Closing'), ('reminder', 'Reminder'), ('explain', 'Exercise Explanation')], default='', help_text='Video type for R2 organization', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videoclip',
            name='script_text',
            field=models.TextField(blank=True, help_text='Video script or content'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='ai_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='videoclip',
            name='archetype',
            field=models.CharField(choices=[('peer', 'Ровесник'), ('professional', 'Успешный профессионал'), ('mentor', 'Мудрый наставник')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='videoclip',
            index=models.Index(fields=['exercise', 'r2_kind', 'archetype'], name='video_clips_exercis_1e5613_idx'),
        ),
        migrations.AddIndex(
            model_name='videoclip',
            index=models.Index(fields=['r2_kind', 'archetype'], name='video_clips_r2_kind_d2e4dd_idx'),
        ),
        migrations.AddIndex(
            model_name='videoclip',
            index=models.Index(fields=['is_active', 'r2_kind'], name='video_clips_is_acti_9705f9_idx'),
        ),
        migrations.RemoveField(
            model_name='videoclip',
            name='type',
        ),
        migrations.RemoveField(
            model_name='videoclip',
            name='url',
        ),
    ]
