# Generated by Django 5.0.6 on 2025-08-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False  # Important for SQLite

    dependencies = [
        ('workouts', '0013_finalvideo_exercise_equipment_exercise_poster_image_and_more'),
    ]

    operations = [
        # First: Drop all problematic indexes/constraints that reference 'type' field
        migrations.RunSQL(
            sql="""
            -- Drop any unique constraints that reference the 'type' field
            DROP INDEX IF EXISTS video_clips_exercise_id_type_archetype_model_name_reminder_text_4f6cb9f6_uniq;
            DROP INDEX IF EXISTS video_clips_exercis_cde9f7_idx;
            -- Drop any other indexes that might reference 'type'
            DROP INDEX IF EXISTS idx_videoclip_type;
            DROP INDEX IF EXISTS videoclip_type_idx;
            """,
            reverse_sql="-- Cannot reverse index drops"
        ),
        
        # Now safe to remove legacy URL fields from Exercise
        migrations.RemoveField(
            model_name='exercise',
            name='technique_video_url',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='mistake_video_url',
        ),
        
        # Remove legacy fields from VideoClip (now safe after index drops)
        migrations.RemoveField(
            model_name='videoclip',
            name='url',
        ),
        migrations.RemoveField(
            model_name='videoclip',
            name='type',
        ),
        
        # Update archetype choices to only include new ones
        migrations.AlterField(
            model_name='videoclip',
            name='archetype',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('peer', 'Ровесник'),
                    ('professional', 'Успешный профессионал'), 
                    ('mentor', 'Мудрый наставник'),
                ]
            ),
        ),
        migrations.AlterField(
            model_name='videoclip',
            name='r2_archetype',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('peer', 'Ровесник'),
                    ('professional', 'Успешный профессионал'),
                    ('mentor', 'Мудрый наставник'),
                ],
                blank=True,
                help_text='Archetype for R2 videos'
            ),
        ),
        
        # Make r2_kind required (was optional)
        migrations.AlterField(
            model_name='videoclip',
            name='r2_kind',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('technique', 'Technique'),
                    ('mistake', 'Common Mistake'),
                    ('instruction', 'Instruction'),
                    ('intro', 'Introduction'),
                    ('weekly', 'Weekly Motivation'),
                    ('closing', 'Closing'),
                    ('reminder', 'Reminder'),
                    ('explain', 'Exercise Explanation'),
                ],
                help_text='Video type for R2 organization'
            ),
        ),
        
        # Indexes will be created by Django from model Meta.indexes
    ]
