# Generated by Django 5.0.8 on 2024-08-09 00:00
# State-only migration to ensure model state is correct after v2 schema

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0013_v2_schema'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # No database operations - tables already created by 0013_v2_schema
            ],
            state_operations=[
                migrations.CreateModel(
                    name='FinalVideo',
                    fields=[
                        ('arch', models.CharField(max_length=20, primary_key=True, serialize=False)),
                        ('locale', models.CharField(default='ru', max_length=5)),
                        ('script', models.TextField()),
                    ],
                    options={'db_table': 'final_videos'},
                ),
                migrations.CreateModel(
                    name='WeeklyLesson',
                    fields=[
                        ('id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('week', models.SmallIntegerField()),
                        ('archetype', models.CharField(max_length=3)),
                        ('locale', models.CharField(default='ru', max_length=5)),
                        ('title', models.CharField(max_length=120)),
                        ('script', models.TextField()),
                        ('duration_sec', models.IntegerField(default=180)),
                    ],
                    options={
                        'db_table': 'weekly_lessons',
                        'constraints': [
                            models.UniqueConstraint(
                                fields=['week', 'archetype', 'locale'],
                                name='unique_weekly_lesson'
                            ),
                        ],
                    },
                ),
            ],
        ),
    ]