# Generated by Django 5.0.6 on 2025-08-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False  # Important for SQLite

    dependencies = [
        ('workouts', '0014_clean_v1_legacy'),
    ]

    operations = [
        # Remove any remaining old indexes conditionally (they may have been already dropped in 0014)  
        migrations.RunSQL(
            sql="""
            DROP INDEX IF EXISTS video_clips_exercis_cde9f7_idx;
            """,
            reverse_sql="-- Cannot reverse index drops"
        ),
        
        # Add missing fields that didn't get created properly from migration 0013
        migrations.RunSQL(
            sql="""
            -- Add r2_kind if it doesn't exist
            ALTER TABLE video_clips ADD COLUMN r2_kind varchar(20) DEFAULT '';
            -- Add r2_file if it doesn't exist
            ALTER TABLE video_clips ADD COLUMN r2_file varchar(100) DEFAULT '';
            -- Add script_text if it doesn't exist  
            ALTER TABLE video_clips ADD COLUMN script_text text DEFAULT '';
            """,
            reverse_sql="-- Cannot reverse column additions in SQLite"
        ),
        
        # Update r2_kind to have proper choices and remove default
        migrations.AlterField(
            model_name='videoclip',
            name='r2_kind',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('technique', 'Technique'),
                    ('mistake', 'Common Mistake'),
                    ('instruction', 'Instruction'),
                    ('intro', 'Introduction'),
                    ('weekly', 'Weekly Motivation'),
                    ('closing', 'Closing'),
                    ('reminder', 'Reminder'),
                    ('explain', 'Exercise Explanation'),
                ],
                help_text='Video type for R2 organization'
            ),
        ),
        
        # Add optimized indexes for v2
        migrations.AddIndex(
            model_name='videoclip',
            index=models.Index(fields=['exercise', 'r2_kind', 'archetype'], name='video_clips_exercis_1e5613_idx'),
        ),
        migrations.AddIndex(
            model_name='videoclip',
            index=models.Index(fields=['r2_kind', 'archetype'], name='video_clips_r2_kind_d2e4dd_idx'),
        ),
        migrations.AddIndex(
            model_name='videoclip',
            index=models.Index(fields=['is_active', 'r2_kind'], name='video_clips_is_acti_9705f9_idx'),
        ),
        
        # Finally create new unique constraint with all required fields
        migrations.RunSQL(
            sql="""
            CREATE UNIQUE INDEX IF NOT EXISTS video_clips_unique_v2_idx 
            ON video_clips (exercise_id, r2_kind, archetype, model_name, reminder_text);
            """,
            reverse_sql="DROP INDEX IF EXISTS video_clips_unique_v2_idx;"
        ),
    ]
