# Generated by Django 5.0.6 on 2025-08-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0016_add_video_provider_fields'),
    ]

    operations = [
        # Add CheckConstraints to ensure provider field consistency with storage fields
        migrations.AddConstraint(
            model_name='videoclip',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(provider='r2', r2_file__isnull=False) |
                    models.Q(provider='stream', stream_uid__isnull=False) |
                    models.Q(provider='stream', playback_id__isnull=False) |
                    models.Q(provider='external')  # Future: no constraints for external yet
                ),
                name='provider_storage_consistency'
            ),
        ),
        
        # Ensure R2 provider has required fields
        migrations.AddConstraint(
            model_name='videoclip',
            constraint=models.CheckConstraint(
                check=models.Q(
                    ~models.Q(provider='r2') | 
                    models.Q(provider='r2', r2_file__isnull=False)
                ),
                name='r2_provider_has_file'
            ),
        ),
        
        # Ensure Stream provider has at least one identifier
        migrations.AddConstraint(
            model_name='videoclip',
            constraint=models.CheckConstraint(
                check=models.Q(
                    ~models.Q(provider='stream') |
                    models.Q(
                        provider='stream',
                        stream_uid__isnull=False
                    ) |
                    models.Q(
                        provider='stream', 
                        playback_id__isnull=False
                    )
                ),
                name='stream_provider_has_identifier'
            ),
        ),
    ]
