# Generated by Django 5.0.6 on 2025-08-09 21:00

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0017_add_provider_constraints'),
    ]

    operations = [
        # Fix unique_together constraint to use 'archetype' instead of 'r2_archetype'
        migrations.AlterUniqueTogether(
            name='videoclip',
            unique_together={('exercise', 'r2_kind', 'archetype', 'model_name', 'reminder_text')},
        ),
        
        # Update indexes to use 'archetype' instead of 'r2_archetype'
        migrations.RemoveIndex(
            model_name='videoclip',
            name='video_clips_exercis_1e5613_idx',
        ),
        migrations.RemoveIndex(
            model_name='videoclip',
            name='video_clips_r2_kind_d2e4dd_idx',
        ),
        
        migrations.AddIndex(
            model_name='videoclip',
            index=models.Index(
                fields=['exercise', 'r2_kind', 'archetype'], 
                name='workouts_videoclip_exercise_r2kind_arch_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='videoclip',
            index=models.Index(
                fields=['r2_kind', 'archetype'], 
                name='workouts_videoclip_r2kind_arch_idx'
            ),
        ),
    ]