# Generated by Django 5.0.6 on 2025-08-10 15:46

import apps.workouts.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0018_fix_unique_constraint_archetype_field'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='videoclip',
            name='provider_storage_consistency',
        ),
        migrations.RemoveConstraint(
            model_name='videoclip',
            name='r2_provider_has_file',
        ),
        migrations.RemoveConstraint(
            model_name='videoclip',
            name='stream_provider_has_identifier',
        ),
        migrations.RenameIndex(
            model_name='videoclip',
            new_name='video_clips_exercis_1e5613_idx',
            old_name='workouts_videoclip_exercise_r2kind_arch_idx',
        ),
        migrations.RenameIndex(
            model_name='videoclip',
            new_name='video_clips_r2_kind_d2e4dd_idx',
            old_name='workouts_videoclip_r2kind_arch_idx',
        ),
# Field ai_analysis already exists, skipping AddField operation
        migrations.AlterField(
            model_name='videoclip',
            name='r2_kind',
            field=models.CharField(choices=[('technique', 'Technique'), ('mistake', 'Mistake'), ('instruction', 'Instruction'), ('intro', 'Intro'), ('weekly', 'Weekly'), ('closing', 'Closing'), ('reminder', 'Reminder'), ('explain', 'Explain')], default=apps.workouts.constants.VideoKind['INSTRUCTION'], help_text='Video type for R2 organization', max_length=20),
        ),
    ]
