# Generated by Django 5.0.6 on 2025-08-10 20:58

from django.db import migrations, models


def safe_remove_constraint(apps, schema_editor):
    """Safely remove unique_weekly_lesson constraint if it exists"""
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            # Check if constraint exists first
            cursor.execute("""
                SELECT 1 
                FROM information_schema.table_constraints 
                WHERE constraint_name = 'unique_weekly_lesson' 
                AND table_name = 'weekly_lessons'
            """)
            if cursor.fetchone():
                cursor.execute("""
                    ALTER TABLE weekly_lessons 
                    DROP CONSTRAINT IF EXISTS unique_weekly_lesson
                """)


def safe_add_is_active_field(apps, schema_editor):
    """Safely add is_active field to CSVExercise if it doesn't exist"""
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            # Check if is_active field exists in csv_exercises
            cursor.execute("""
                SELECT 1 
                FROM information_schema.columns 
                WHERE table_name = 'csv_exercises' 
                AND column_name = 'is_active'
            """)
            if not cursor.fetchone():
                cursor.execute("""
                    ALTER TABLE csv_exercises 
                    ADD COLUMN is_active boolean DEFAULT true NOT NULL
                """)


def reverse_add_is_active_field(apps, schema_editor):
    """Reverse operation for adding is_active field"""
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                ALTER TABLE csv_exercises 
                DROP COLUMN IF EXISTS is_active
            """)


def reverse_remove_constraint(apps, schema_editor):
    """Reverse operation - this is a no-op since we can't recreate the constraint safely"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0019_remove_videoclip_provider_storage_consistency_and_more'),
    ]

    operations = [
        migrations.RunPython(
            safe_remove_constraint,
            reverse_remove_constraint,
            atomic=False,
        ),
        migrations.RunPython(
            safe_add_is_active_field,
            reverse_add_is_active_field,
            atomic=False,
        ),
        # Note: ai_analysis field already exists from migration 0011 and 0013
        # Skipping AddField operation for workoutplan.ai_analysis
    ]