# Generated by Django 5.0.6 on 2025-08-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0019_remove_videoclip_provider_storage_consistency_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weeklylesson',
            name='unique_weekly_lesson',
        ),
        migrations.AddField(
            model_name='csvexercise',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='ai_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
