# Generated by Django 5.0.6 on 2025-08-10 20:58

from django.db import migrations, models


def safe_remove_constraint(apps, schema_editor):
    """Safely remove unique_weekly_lesson constraint if it exists"""
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            # Check if constraint exists first
            cursor.execute("""
                SELECT 1 
                FROM information_schema.table_constraints 
                WHERE constraint_name = 'unique_weekly_lesson' 
                AND table_name = 'weekly_lessons'
            """)
            if cursor.fetchone():
                cursor.execute("""
                    ALTER TABLE weekly_lessons 
                    DROP CONSTRAINT IF EXISTS unique_weekly_lesson
                """)


def reverse_remove_constraint(apps, schema_editor):
    """Reverse operation - this is a no-op since we can't recreate the constraint safely"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0019_remove_videoclip_provider_storage_consistency_and_more'),
    ]

    operations = [
        migrations.RunPython(
            safe_remove_constraint,
            reverse_remove_constraint,
            atomic=False,
        ),
        migrations.AddField(
            model_name='csvexercise',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='ai_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
    ]