# Generated by Django 5.0.6 on 2025-08-11 18:12

import apps.workouts.constants
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0021_sync_model_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField(help_text='Week number in the course (1-8)', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('theme_title', models.CharField(help_text='Title of the weekly theme', max_length=100)),
                ('focus_area', models.CharField(help_text='Main focus area for the week', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of weekly objectives')),
                ('mentor_content', models.TextField(blank=True, help_text='Content adapted for mentor archetype')),
                ('professional_content', models.TextField(blank=True, help_text='Content adapted for professional archetype')),
                ('peer_content', models.TextField(blank=True, help_text='Content adapted for peer archetype')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'weekly_themes',
                'ordering': ['week_number'],
            },
        ),
        migrations.AddField(
            model_name='videoclip',
            name='content_theme',
            field=models.CharField(blank=True, choices=[('week_start', 'Начало недели'), ('overcoming', 'Преодоление'), ('gratitude', 'Благодарность'), ('motivation', 'Мотивация'), ('recovery', 'Восстановление'), ('achievement', 'Достижение'), ('consistency', 'Постоянство'), ('challenge', 'Вызов')], help_text='Тематика контента', max_length=30),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='mood_type',
            field=models.CharField(blank=True, choices=[('energetic', 'Энергичное'), ('philosophical', 'Философское'), ('business', 'Деловое'), ('encouraging', 'Ободряющее'), ('calm', 'Спокойное')], help_text='Настроение/тон видео', max_length=20),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='position_in_workout',
            field=models.CharField(blank=True, choices=[('intro', 'Вступление'), ('mid', 'Середина'), ('outro', 'Завершение')], help_text='Позиция в тренировке', max_length=15),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='variation_number',
            field=models.PositiveIntegerField(default=1, help_text='Номер вариации (для множественных intro/outro)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='week_context',
            field=models.PositiveIntegerField(blank=True, help_text='Номер недели курса (1-8)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='videoclip',
            name='r2_kind',
            field=models.CharField(choices=[('technique', 'Technique'), ('mistake', 'Mistake'), ('instruction', 'Instruction'), ('intro', 'Intro'), ('weekly', 'Weekly'), ('closing', 'Closing'), ('reminder', 'Reminder'), ('explain', 'Explain'), ('contextual_intro', 'Contextual_Intro'), ('contextual_outro', 'Contextual_Outro'), ('mid_workout', 'Mid_Workout'), ('theme_based', 'Theme_Based'), ('motivational_break', 'Motivational_Break')], default=apps.workouts.constants.VideoKind['INSTRUCTION'], help_text='Video type for R2 organization', max_length=20),
        ),
    ]
