# Generated by Django 5.0.6 on 2025-08-11 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0022_add_contextual_video_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoclip',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_clips', to='workouts.csvexercise'),
        ),
    ]
