# Generated by Django 5.0.8 on 2025-08-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0024_expand_exercise_name_lengths"),
    ]

    operations = [
        migrations.AlterField(
            model_name="csvexercise",
            name="exercise_type",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="csvexercise",
            name="muscle_group",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="csvexercise",
            name="name_en",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
