# Generated by Django 5.0.8 on 2025-08-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_url", models.URLField()),
                ("file_size", models.PositiveIntegerField(help_text="Size in bytes")),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("image", "Image"),
                            ("audio", "Audio"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("exercise_technique", "Exercise Technique"),
                            ("exercise_mistake", "Exercise Mistake"),
                            ("exercise_instruction", "Exercise Instruction"),
                            ("exercise_reminder", "Exercise Reminder"),
                            ("motivation_intro", "Daily Intro"),
                            ("motivation_weekly", "Weekly Motivation"),
                            ("motivation_progress", "Progress Milestone"),
                            ("motivation_final", "Final Congratulation"),
                            ("card_background", "Motivational Card Background"),
                            ("avatar", "Trainer Avatar"),
                            ("story_cover", "Story Cover"),
                            ("story_chapter", "Story Chapter Image"),
                        ],
                        max_length=30,
                    ),
                ),
                ("tags", models.JSONField(default=list)),
                (
                    "archetype",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bro", "Бро"),
                            ("sergeant", "Сержант"),
                            ("intellectual", "Интеллектуал"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True, help_text="For videos/audio", null=True
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True, help_text="For images/videos", null=True
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True, help_text="For images/videos", null=True
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("cdn_url", models.URLField(blank=True)),
                (
                    "cdn_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "media_assets",
            },
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("cover_image_url", models.URLField()),
                ("total_chapters", models.PositiveIntegerField()),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Stories",
                "db_table": "stories",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="StoryChapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chapter_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "estimated_reading_time",
                    models.PositiveIntegerField(help_text="In minutes"),
                ),
                ("image_url", models.URLField(blank=True)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "story_chapters",
                "ordering": ["chapter_number"],
            },
        ),
        migrations.CreateModel(
            name="UserStoryAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                ("first_read_at", models.DateTimeField(blank=True, null=True)),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                ("read_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "user_story_access",
            },
        ),
    ]
