# Generated by Django 5.0.8 on 2025-08-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LandingContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(default="2.0", max_length=20, unique=True),
                ),
                ("hero_title", models.CharField(max_length=200)),
                ("hero_subtitle", models.TextField()),
                ("hero_cta_primary", models.CharField(max_length=50)),
                ("hero_cta_secondary", models.CharField(blank=True, max_length=50)),
                ("for_whom", models.TextField(help_text="Who is this app for?")),
                ("how_it_works", models.TextField(help_text="How the app works")),
                (
                    "safety",
                    models.TextField(help_text="Safety and confidence information"),
                ),
                (
                    "personalization",
                    models.TextField(help_text="Personalization features"),
                ),
                (
                    "cases",
                    models.JSONField(
                        default=list, help_text="List of use cases or success stories"
                    ),
                ),
                (
                    "features",
                    models.JSONField(default=list, help_text="List of key features"),
                ),
                ("footer_text", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "landing_content",
                "ordering": ["-version"],
            },
        ),
    ]
