# Generated by Django 5.0.8 on 2025-08-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaasset",
            name="category",
            field=models.CharField(
                choices=[
                    ("exercise_technique", "Exercise Technique"),
                    ("exercise_mistake", "Exercise Mistake"),
                    ("exercise_instruction", "Exercise Instruction"),
                    ("exercise_reminder", "Exercise Reminder"),
                    ("motivation_intro", "Daily Intro"),
                    ("motivation_weekly", "Weekly Motivation"),
                    ("motivation_progress", "Progress Milestone"),
                    ("motivation_final", "Final Congratulation"),
                    ("card_background", "Motivational Card Background"),
                    ("avatar", "Trainer Avatar"),
                    ("story_cover", "Story Cover"),
                    ("story_chapter", "Story Chapter Image"),
                ],
                max_length=30,
            ),
        ),
    ]
