# Generated by Django 5.0.6 on 2025-07-22 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achievements', '0003_initial'),
        ('content', '0001_initial'),
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='workouts.exercise'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storychapter',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='content.story'),
        ),
        migrations.AddField(
            model_name='userstoryaccess',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.storychapter'),
        ),
        migrations.AddField(
            model_name='userstoryaccess',
            name='unlocked_by_achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='achievements.achievement'),
        ),
        migrations.AddField(
            model_name='userstoryaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['category', 'asset_type'], name='media_asset_categor_71eb8a_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['exercise', 'category'], name='media_asset_exercis_fe6f18_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storychapter',
            unique_together={('story', 'chapter_number')},
        ),
        migrations.AddIndex(
            model_name='userstoryaccess',
            index=models.Index(fields=['user', 'chapter'], name='user_story__user_id_1c9c38_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userstoryaccess',
            unique_together={('user', 'chapter')},
        ),
    ]
