# Generated by Django 5.0.6 on 2025-08-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='2.0', max_length=20, unique=True)),
                ('hero_title', models.CharField(max_length=200)),
                ('hero_subtitle', models.TextField()),
                ('hero_cta_primary', models.CharField(max_length=50)),
                ('hero_cta_secondary', models.CharField(blank=True, max_length=50)),
                ('for_whom', models.TextField(help_text='Who is this app for?')),
                ('how_it_works', models.TextField(help_text='How the app works')),
                ('safety', models.TextField(help_text='Safety and confidence information')),
                ('personalization', models.TextField(help_text='Personalization features')),
                ('cases', models.JSONField(default=list, help_text='List of use cases or success stories')),
                ('features', models.JSONField(default=list, help_text='List of key features')),
                ('footer_text', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'landing_content',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='TrainerPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('archetype', models.CharField(choices=[('peer', 'Ровесник'), ('professional', 'Успешный профессионал'), ('mentor', 'Мудрый наставник'), ('bro', 'Бро (Legacy)'), ('sergeant', 'Сержант (Legacy)'), ('intellectual', 'Интеллектуал (Legacy)')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tone_guidelines', models.TextField(help_text='Guidelines for AI tone and communication style')),
                ('motivational_style', models.TextField(help_text='How this trainer motivates users')),
                ('avatar', models.ImageField(blank=True, help_text='Trainer avatar image', null=True, upload_to='images/avatars/')),
                ('avatar_url', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trainer_personas',
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
