# Generated by Django 5.0.8 on 2025-08-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storychapter",
            options={"ordering": ["order"]},
        ),
        migrations.RenameField(
            model_name="storychapter",
            old_name="chapter_number",
            new_name="order",
        ),
        migrations.AlterUniqueTogether(
            name="storychapter",
            unique_together={("story", "order")},
        ),
        migrations.AddField(
            model_name="story",
            name="genre",
            field=models.CharField(default="romance", max_length=50),
        ),
        migrations.AddField(
            model_name="storychapter",
            name="thumbnail_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="storychapter",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="storychapter",
            name="video_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="story",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="storychapter",
            name="estimated_reading_time",
            field=models.PositiveIntegerField(default=5, help_text="In minutes"),
        ),
    ]
