# Generated by Django during database audit cleanup

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_landingcontent_trainerpersona'),  # Updated to actual latest migration
    ]

    operations = [
        # Update MediaAsset archetype choices to use new format
        migrations.AlterField(
            model_name='mediaasset',
            name='archetype',
            field=models.CharField(
                blank=True,
                choices=[
                    ('peer', 'Лучший друг'),
                    ('professional', 'Профессиональный тренер'),
                    ('mentor', 'Мудрый наставник'),
                ],
                max_length=20
            ),
        ),
        
        # Remove deprecated avatar_url field from TrainerPersona
        migrations.RemoveField(
            model_name='trainerpersona',
            name='avatar_url',
        ),
    ]