# Generated by Django 5.0.8 on 2025-08-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='category',
            field=models.CharField(choices=[('exercise_technique', 'Exercise Technique'), ('exercise_mistake', 'Exercise Mistake'), ('exercise_instruction', 'Exercise Instruction'), ('exercise_reminder', 'Exercise Reminder'), ('motivation_weekly', 'Weekly Motivation'), ('motivation_final', 'Final Congratulation'), ('card_background', 'Motivational Card Background'), ('avatar', 'Trainer Avatar'), ('misc', 'Miscellaneous'), ('intro', 'Intro'), ('warmup', 'Warm-up'), ('main_block', 'Main Block'), ('cooldown', 'Cooldown / Stretch'), ('transition', 'Transition / Separator'), ('timer', 'Timer / Beep'), ('motivation', 'Motivational'), ('breathing', 'Breathing')], max_length=30),
        ),
    ]
