# Generated by Django 5.0.6 on 2025-08-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_unify_archetype_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='archetype',
            field=models.CharField(choices=[('111', 'Наставник'), ('222', 'Профессионал'), ('333', 'Ровесник')], default='111', max_length=3),
        ),
    ]
