# Generated by Django 5.0.6 on 2025-08-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_convert_archetype_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='archetype',
            field=models.CharField(choices=[('mentor', 'Мудрый наставник'), ('professional', 'Успешный профессионал'), ('peer', 'Ровесник')], default='mentor', max_length=20),
        ),
    ]
