# Generated by Django 5.0.6 on 2025-07-15 12:08

from django.db import migrations, models


def set_completed_onboarding(apps, schema_editor):
    """Set completed_onboarding based on existing onboarding data"""
    User = apps.get_model('users', 'User')
    
    # Update users who have completed onboarding
    User.objects.filter(
        onboarding_completed_at__isnull=False,
        archetype__isnull=False
    ).exclude(archetype='').update(completed_onboarding=True)


def reverse_completed_onboarding(apps, schema_editor):
    """Reverse the completed_onboarding field"""
    User = apps.get_model('users', 'User')
    User.objects.all().update(completed_onboarding=False)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_reset_onboarding_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_onboarding',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            set_completed_onboarding,
            reverse_completed_onboarding
        ),
    ]
