# Generated by Django 5.0.6 on 2025-07-15 12:43

from django.db import migrations


def fix_onboarding_status(apps, schema_editor):
    """Fix onboarding status for users who marked as complete but missing required data"""
    User = apps.get_model('users', 'User')
    WorkoutPlan = apps.get_model('workouts', 'WorkoutPlan')
    
    # Find users marked as completed_onboarding=True but missing archetype or active plan
    users_to_fix = User.objects.filter(completed_onboarding=True)
    
    fixed_count = 0
    for user in users_to_fix:
        # Check if user has active workout plan
        has_active_plan = WorkoutPlan.objects.filter(user=user, is_active=True).exists()
        
        # If missing archetype or no active plan, reset onboarding
        if not user.archetype or not has_active_plan:
            user.completed_onboarding = False
            user.onboarding_completed_at = None
            user.save(update_fields=['completed_onboarding', 'onboarding_completed_at'])
            fixed_count += 1
    
    print(f"Fixed onboarding status for {fixed_count} users")


def reverse_fix_onboarding_status(apps, schema_editor):
    """Reverse migration - do nothing as we can't restore incorrect state"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_completed_onboarding_field'),
        ('workouts', '0003_weeklyfeedback'),  # Ensure WorkoutPlan table exists
    ]

    operations = [
        migrations.RunPython(
            fix_onboarding_status,
            reverse_fix_onboarding_status,
        ),
    ]
