# Generated by Django 5.0.6 on 2025-07-23 17:44

from django.db import migrations


def remove_archetype_column(apps, schema_editor):
    """Remove archetype column from users table if it exists"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE users DROP COLUMN IF EXISTS archetype;
        """)


def reverse_remove_archetype_column(apps, schema_editor):
    """This migration is not reversible"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_create_missing_profiles'),
    ]

    operations = [
        migrations.RunPython(remove_archetype_column, reverse_remove_archetype_column),
    ]
