# Generated by Django 5.0.6 on 2025-07-23 18:01

from django.db import migrations
import logging

logger = logging.getLogger(__name__)


def diagnose_users_table(apps, schema_editor):
    """Check the actual structure of users table"""
    with schema_editor.connection.cursor() as cursor:
        # Get table schema
        cursor.execute("""
            SELECT column_name, data_type, is_nullable, column_default
            FROM information_schema.columns 
            WHERE table_name = 'users' 
            ORDER BY ordinal_position;
        """)
        columns = cursor.fetchall()
        
        logger.error("=== USERS TABLE STRUCTURE ===")
        for col in columns:
            logger.error(f"Column: {col[0]}, Type: {col[1]}, Nullable: {col[2]}, Default: {col[3]}")
        logger.error("=============================")


def reverse_diagnose_users_table(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20250723_1755'),
    ]

    operations = [
        migrations.RunPython(diagnose_users_table, reverse_diagnose_users_table),
    ]
