# Generated by Django 5.0.6 on 2025-07-31 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingquestion',
            name='block_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='onboardingquestion',
            name='block_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='onboardingquestion',
            name='depends_on_answer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='onboardingquestion',
            name='depends_on_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_questions', to='onboarding.onboardingquestion'),
        ),
        migrations.AddField(
            model_name='onboardingquestion',
            name='is_block_separator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboardingquestion',
            name='scale_max_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='onboardingquestion',
            name='scale_min_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='onboardingquestion',
            name='separator_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='useronboardingresponse',
            name='answer_body_map',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useronboardingresponse',
            name='answer_scale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingquestion',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('number', 'Number Input'), ('text', 'Text Input'), ('scale', 'Scale (1-5)'), ('body_map', 'Body Map Selection')], max_length=20),
        ),
    ]
