# Generated by Django 5.0.8 on 2025-08-29 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("onboarding", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="onboardingsession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="onboarding_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="useronboardingresponse",
            name="answer_options",
            field=models.ManyToManyField(blank=True, to="onboarding.answeroption"),
        ),
        migrations.AddField(
            model_name="useronboardingresponse",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="onboarding.onboardingquestion",
            ),
        ),
        migrations.AddField(
            model_name="useronboardingresponse",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="onboarding_responses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="motivationalcard",
            unique_together={("question", "answer_option")},
        ),
        migrations.AlterUniqueTogether(
            name="answeroption",
            unique_together={("question", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="useronboardingresponse",
            unique_together={("user", "question")},
        ),
    ]
