# Generated by Django 5.0.8 on 2025-08-24 10:42

from django.db import migrations


def fix_question_5_separator(apps, schema_editor):
    """Fix question 5 to show answer options instead of being a block separator"""
    OnboardingQuestion = apps.get_model('onboarding', 'OnboardingQuestion')
    
    try:
        question = OnboardingQuestion.objects.get(order=5)
        # Ensure it's not a block separator so answer options are shown
        question.is_block_separator = False
        question.separator_text = ''
        # Ensure it's single_choice type
        question.question_type = 'single_choice'
        question.save(update_fields=['is_block_separator', 'separator_text', 'question_type'])
    except OnboardingQuestion.DoesNotExist:
        pass  # Question doesn't exist, nothing to fix


def reverse_fix_question_5(apps, schema_editor):
    """Reverse the fix (for rollback)"""
    # No reverse action needed as we don't want to break it again
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0002_squashed_compat"),
    ]

    operations = [
        migrations.RunPython(
            fix_question_5_separator,
            reverse_fix_question_5
        ),
    ]
