# Generated by Django 5.0.6 on 2025-07-31 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_conditional_schema_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivationalcard',
            name='answer_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motivational_cards', to='onboarding.answeroption'),
        ),
        migrations.AddField(
            model_name='motivationalcard',
            name='is_default_for_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='motivationalcard',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motivational_cards', to='onboarding.onboardingquestion'),
        ),
        migrations.AlterField(
            model_name='motivationalcard',
            name='category',
            field=models.CharField(choices=[('goal', 'Goal-related'), ('experience', 'Experience-related'), ('limitation', 'Limitation-related'), ('general', 'General motivation'), ('response', 'Response-specific')], default='response', max_length=50),
        ),
        migrations.AlterField(
            model_name='motivationalcard',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='motivationalcard',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='motivationalcard',
            unique_together={('question', 'answer_option')},
        ),
    ]
