# Generated by Django 5.0.8 on 2025-08-18 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingquestion',
            name='block_name',
            field=models.CharField(max_length=200, blank=True, default=''),
        ),
        migrations.AddField(
            model_name='onboardingquestion',
            name='block_order',
            field=models.PositiveIntegerField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='onboardingquestion',
            name='is_block_separator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onboardingquestion',
            name='separator_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='onboardingquestion',
            name='scale_min_label',
            field=models.CharField(max_length=100, blank=True, default=''),
        ),
        migrations.AddField(
            model_name='onboardingquestion',
            name='scale_max_label',
            field=models.CharField(max_length=100, blank=True, default=''),
        ),
    ]
