# Generated by Django 5.0.6 on 2025-08-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_motivationalcard_answer_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivationalcard',
            name='image',
            field=models.ImageField(blank=True, help_text='Motivational card image', null=True, upload_to='photos/quotes/'),
        ),
    ]
