# Generated by Django 5.0.8 on 2025-08-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0004_add_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboardingquestion",
            name="block_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="onboardingquestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("single_choice", "Single Choice"),
                    ("multiple_choice", "Multiple Choice"),
                    ("number", "Number Input"),
                    ("text", "Text Input"),
                    ("scale", "Scale Rating"),
                    ("body_map", "Body Map Selection"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="onboardingquestion",
            name="scale_max_label",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="onboardingquestion",
            name="scale_min_label",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="onboardingquestion",
            name="separator_text",
            field=models.TextField(blank=True),
        ),
    ]
