# Generated by Django 5.0.6 on 2025-08-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_motivationalcard_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivationalcard',
            name='path',
            field=models.CharField(blank=True, help_text='Relative path to image in R2 storage (e.g., "photos/quotes/card_quotes_0170.jpg")', max_length=500),
        ),
        migrations.AlterField(
            model_name='motivationalcard',
            name='image',
            field=models.ImageField(blank=True, help_text='DEPRECATED: Use path field instead', null=True, upload_to='photos/quotes/'),
        ),
        migrations.AlterField(
            model_name='motivationalcard',
            name='image_url',
            field=models.URLField(blank=True, help_text='DEPRECATED: Use path field instead'),
        ),
    ]
