# Generated by Django during database audit cleanup

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_auto_20241201_1200'),  # Update this to your latest migration
    ]

    operations = [
        # Remove deprecated image_url field from MotivationalCard
        migrations.RemoveField(
            model_name='motivationalcard',
            name='image_url',
        ),
        
        # Remove deprecated image field from MotivationalCard
        migrations.RemoveField(
            model_name='motivationalcard',
            name='image',
        ),
    ]