# Generated by Django 5.0.8 on 2025-08-29 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticsevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsmetrics",
            index=models.Index(
                fields=["metric_type", "metric_date"],
                name="analytics_m_metric__cf9b1a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsmetrics",
            index=models.Index(
                fields=["metric_date"], name="analytics_m_metric__579da0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="analyticsmetrics",
            unique_together={("metric_type", "metric_date", "dimension_filters")},
        ),
        migrations.AddField(
            model_name="usersession",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["user", "event_time"], name="analytics_e_user_id_8b61b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["event_type", "event_time"],
                name="analytics_e_event_t_6ac541_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["event_time"], name="analytics_e_event_t_b93e62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["session_id"], name="analytics_e_session_b3cbf5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["device_id"], name="analytics_e_device__66395a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["amplitude_sent"], name="analytics_e_amplitu_13156a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "started_at"], name="user_sessio_user_id_30ad4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["session_id"], name="user_sessio_session_e62ba3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["started_at"], name="user_sessio_started_8c462e_idx"
            ),
        ),
    ]
