# Generated by Django 5.0.6 on 2025-08-06 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('onesignal', 'OneSignal'), ('fcm', 'Firebase Cloud Messaging')], default='onesignal', max_length=20)),
                ('platform', models.CharField(choices=[('web', 'Web Browser'), ('ios', 'iOS App'), ('android', 'Android App')], default='web', max_length=10)),
                ('subscription_id', models.CharField(max_length=200, unique=True)),
                ('endpoint', models.URLField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'push_subscriptions',
            },
        ),
        migrations.CreateModel(
            name='PushNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent Successfully'), ('failed', 'Failed'), ('delivered', 'Delivered'), ('clicked', 'Clicked')], default='pending', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=200)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='notifications.pushsubscription')),
            ],
            options={
                'db_table': 'push_notification_logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['user', 'is_active'], name='push_subscr_user_id_c81a15_idx'),
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['subscription_id'], name='push_subscr_subscri_a4f152_idx'),
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['provider', 'platform'], name='push_subscr_provide_19b75a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pushsubscription',
            unique_together={('user', 'subscription_id')},
        ),
        migrations.AddIndex(
            model_name='pushnotificationlog',
            index=models.Index(fields=['subscription', 'status'], name='push_notifi_subscri_f9c252_idx'),
        ),
        migrations.AddIndex(
            model_name='pushnotificationlog',
            index=models.Index(fields=['sent_at'], name='push_notifi_sent_at_f74809_idx'),
        ),
        migrations.AddIndex(
            model_name='pushnotificationlog',
            index=models.Index(fields=['provider_message_id'], name='push_notifi_provide_f5ee9f_idx'),
        ),
    ]
