# Generated by Django 5.0.8 on 2025-08-29 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pushsubscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="push_subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pushnotificationlog",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_logs",
                to="notifications.pushsubscription",
            ),
        ),
        migrations.AddIndex(
            model_name="pushsubscription",
            index=models.Index(
                fields=["user", "is_active"], name="push_subscr_user_id_c81a15_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pushsubscription",
            index=models.Index(
                fields=["subscription_id"], name="push_subscr_subscri_a4f152_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pushsubscription",
            index=models.Index(
                fields=["provider", "platform"], name="push_subscr_provide_19b75a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pushsubscription",
            unique_together={("user", "subscription_id")},
        ),
        migrations.AddIndex(
            model_name="pushnotificationlog",
            index=models.Index(
                fields=["subscription", "status"], name="push_notifi_subscri_f9c252_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pushnotificationlog",
            index=models.Index(
                fields=["sent_at"], name="push_notifi_sent_at_f74809_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pushnotificationlog",
            index=models.Index(
                fields=["provider_message_id"], name="push_notifi_provide_f5ee9f_idx"
            ),
        ),
    ]
